// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prodest.EOuv.Infra.DAL.Temp
{
    public partial class AgenteManifestacao
    {
        public AgenteManifestacao()
        {
            DespachoManifestacaoIdAgenteDestinatarioNavigation = new HashSet<DespachoManifestacao>();
            DespachoManifestacaoIdAgenteRespostaNavigation = new HashSet<DespachoManifestacao>();
        }

        public int IdAgenteManifestacao { get; set; }
        public int TipoAgente { get; set; }
        public string GuidUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public Guid? GuidPapel { get; set; }
        public string NomePapel { get; set; }
        public Guid? GuidGrupo { get; set; }
        public string NomeGrupo { get; set; }
        public Guid? GuidSetor { get; set; }
        public string NomeSetor { get; set; }
        public string SiglaSetor { get; set; }
        public Guid? GuidOrgao { get; set; }
        public string NomeOrgao { get; set; }
        public string SiglaOrgao { get; set; }
        public Guid? GuidPatriarca { get; set; }
        public string NomePatriarca { get; set; }
        public string SiglaPatriarca { get; set; }

        public virtual ICollection<DespachoManifestacao> DespachoManifestacaoIdAgenteDestinatarioNavigation { get; set; }
        public virtual ICollection<DespachoManifestacao> DespachoManifestacaoIdAgenteRespostaNavigation { get; set; }
    }
}